name: chromatic

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history, exact ref)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use PR head SHA when in PRs, otherwise the current commit SHA
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Publish to Chromatic
        run: pnpm chromatic -- --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --only-changed --exit-zero-on-changes
