name: Chromatic

on:
  pull_request: { types: [opened, synchronize, reopened] }
  push:
    branches: [main]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history, exact ref)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }} # lets the app post PR status
          onlyChanged: true # same as --only-changed
          exitOnceUploaded: true # speeds CI (don’t wait for verification)
          buildScriptName: build-storybook # lets the action run your build
