name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel stale runs when a new commit is pushed to the same ref
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install pnpm (reads version from package.json: "packageManager": "pnpm@x.y.z")
      - uses: pnpm/action-setup@v4
      # Setup Node and enable pnpm cache keyed by pnpm-lock.yaml
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm --version
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm --version
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm --version
      - run: pnpm install --frozen-lockfile
      - run: pnpm test:ci
